module.exports = {
  apps: {
    uid: { type: 'string', nullable: false, primary: true },
    name: { type: 'string', nullable: false, unique: true },
    description: { type: 'string', maxlength: 2000, nullable: true },
    slug: { type: 'string', nullable: false, unique: true },
    logo: { type: 'string', maxlength: 2000, nullable: true },
    secret: { type: 'string', nullable: false },
    status: {
      type: 'string',
      maxlength: 50,
      nullable: false,
      defaultTo: 'inactive',
    },
    type: {
      type: 'string',
      maxlength: 50,
      nullable: false,
      defaultTo: 'web',
    },
    created_at: { type: 'dateTime', nullable: false },
    updated_at: { type: 'dateTime', nullable: true },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  users: {
    uid: { type: 'string', nullable: false, primary: true },
    email: {
      type: 'string',
      nullable: false,
      unique: true,
      validations: { isEmail: true },
    },
    firstname: { type: 'string', nullable: true },
    lastname: { type: 'string', nullable: true },
    locale: { type: 'string', maxlength: 6, nullable: true },
    password: { type: 'string', maxlength: 128, nullable: false },
    status: {
      type: 'string',
      maxlength: 50,
      nullable: false,
      defaultTo: 'active',
    },
    updated_at: { type: 'dateTime', nullable: true },
    created_at: { type: 'dateTime', nullable: false },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  roles: {
    uid: { type: 'string', nullable: false, primary: true },
    name: { type: 'string', maxlength: 50, nullable: false, unique: true },
    description: { type: 'string', maxlength: 2000, nullable: true },
    app_uid: { type: 'string', nullable: false, references: 'apps.uid' },
    updated_at: { type: 'dateTime', nullable: true },
    created_at: { type: 'dateTime', nullable: false },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  permissions: {
    uid: { type: 'string', nullable: false, primary: true },
    name: { type: 'string', maxlength: 50, nullable: false, unique: true },
    app_uid: { type: 'string', nullable: false, references: 'apps.uid' },
    object: { type: 'string', maxlength: 50, nullable: false },
    action: { type: 'string', maxlength: 50, nullable: false },
    created_at: { type: 'dateTime', nullable: false },
    updated_at: { type: 'dateTime', nullable: true },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  apps_users: {
    app_uid: { type: 'string', nullable: false },
    user_uid: { type: 'string', nullable: false },
  },
  roles_users: {
    role_uid: { type: 'string', nullable: false },
    user_uid: { type: 'string', nullable: false },
  },
  permissions_roles: {
    role_uid: { type: 'string', nullable: false },
    permission_uid: { type: 'string', nullable: false },
  },
};
