module.exports = {
  apps: {
    uid: { type: 'string', nullable: false, primary: true },
    name: { type: 'string', nullable: false, unique: true },
    slug: { type: 'string', nullable: false, unique: true },
    secret: { type: 'string', nullable: false },
    status: {
      type: 'string',
      maxlength: 50,
      nullable: false,
      defaultTo: 'inactive',
    },
    created_at: { type: 'dateTime', nullable: false },
    updated_at: { type: 'dateTime', nullable: true },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  users: {
    uid: { type: 'string', nullable: false, primary: true },
    email: {
      type: 'string',
      nullable: false,
      unique: true,
      validations: { isEmail: true },
    },
    firstname: { type: 'string', nullable: true },
    lastname: { type: 'string', nullable: true },
    lastname: { type: 'string', nullable: true },
    locale: { type: 'string', maxlength: 6, nullable: true },
    password: { type: 'string', maxlength: 128, nullable: false },
    phone: { type: 'string', nullable: true },
    status: {
      type: 'string',
      maxlength: 50,
      nullable: false,
      defaultTo: 'active',
    },
    updated_at: { type: 'dateTime', nullable: true },
    created_at: { type: 'dateTime', nullable: false },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  roles: {
    uid: { type: 'string', nullable: false, primary: true },
    name: { type: 'string', maxlength: 50, nullable: false, unique: true },
    description: { type: 'string', maxlength: 2000, nullable: true },
    updated_at: { type: 'dateTime', nullable: true },
    created_at: { type: 'dateTime', nullable: false },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  permissions: {
    uid: { type: 'string', nullable: false, primary: true },
    name: { type: 'string', maxlength: 50, nullable: false, unique: true },
    object_type: { type: 'string', maxlength: 50, nullable: false },
    action_type: { type: 'string', maxlength: 50, nullable: false },
    object_id: { type: 'string', maxlength: 24, nullable: true },
    created_at: { type: 'dateTime', nullable: false },
    updated_at: { type: 'dateTime', nullable: true },
    created_by: { type: 'string', nullable: false },
    updated_by: { type: 'string', nullable: true },
  },
  roles_users: {
    role_id: { type: 'string', nullable: false },
    user_id: { type: 'string', nullable: false },
  },
  permissions_users: {
    user_id: { type: 'string', nullable: false },
    permission_id: { type: 'string', nullable: false },
  },
  permissions_roles: {
    role_id: { type: 'string', nullable: false },
    permission_id: { type: 'string', nullable: false },
  },
  permissions_apps: {
    app_id: { type: 'string', nullable: false },
    permission_id: { type: 'string', nullable: false },
  },
};
